# Utilise l'image officielle de Node 20.15
FROM node:20.15-alpine

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers de dépendances
COPY client/package.json client/package-lock.json ./

# Installer les dépendances
RUN npm install

# Copier tout le reste du code du frontend
COPY client ./

# Exposer le port de Nuxt
EXPOSE 3021

# Supprimer les fichiers temporaires et démarrer Nuxt
CMD rm -rf .nuxt /tmp/nitro && npm run dev
