# Utilise l'image officielle de Node
FROM node:23-alpine3.20

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour le backend
COPY server/package.json server/package-lock.json ./

# Installer les dépendances backend avec npm
RUN npm install

# Copier le reste du code backend
COPY server ./

# Exposer le port du backend
EXPOSE 3000

# Lancer l'application NestJS
CMD ["npm", "run", "start:dev"]
