services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nestjs_backend
    ports:
      - "4021:4021"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydatabase

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nuxt_frontend
    ports:
      - "3021:3021"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata: {}  