name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (Backend)
        run: |
          cd server
          npm install

      - name: Run Backend Tests
        run: |
          cd server
          npm run test

      - name: Install dependencies (Frontend)
        run: |
          cd client
          npm install

      - name: Build Frontend
        run: |
          cd client
          npm run build
